Set-StrictMode -Version 2
$ErrorActionPreference='Stop'

function Get-Root { Split-Path $PSScriptRoot -Parent }
function Get-Workspace { $path=Join-Path (Get-Root) 'workspace';New-Item -ItemType Directory -Path $path -Force|Out-Null;return $path }
function Test-ProductId([string]$ProductId){ return $ProductId -match '^\d{5,30}$' }
function Assert-ProductId([string]$ProductId){if(-not(Test-ProductId $ProductId)){throw '商品ID格式錯誤：只能使用5至30位數字，已停止以避免商品串圖。'}}
function Get-ColumnNumber([string]$Reference){$letters=($Reference -replace '\d','').ToUpper();$number=0;foreach($letter in $letters.ToCharArray()){$number=$number*26+([int]$letter-[int][char]'A'+1)};return $number-1}

function Import-ShopeeExcel([string]$Path){
 if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw '找不到 Excel 檔案。'};if([IO.Path]::GetExtension($Path)-ne'.xlsx'){throw '請選擇 .xlsx 格式的蝦皮媒體資訊 Excel。'}
 Add-Type -AssemblyName System.IO.Compression.FileSystem;$archive=$null
 try{
  $archive=[IO.Compression.ZipFile]::OpenRead((Resolve-Path -LiteralPath $Path));$entries=@{};foreach($entry in $archive.Entries){$entries[$entry.FullName]=$entry}
  $sheet=$entries['xl/worksheets/sheet1.xml'];if(-not$sheet){$sheet=($archive.Entries|Where-Object FullName -like 'xl/worksheets/sheet*.xml'|Select-Object -First 1)};if(-not$sheet){throw 'Excel 中找不到工作表。'}
  $shared=@();if($entries['xl/sharedStrings.xml']){$reader=New-Object IO.StreamReader($entries['xl/sharedStrings.xml'].Open());[xml]$xml=$reader.ReadToEnd();$reader.Dispose();foreach($item in $xml.sst.si){$parts=@($item.SelectNodes('.//*[local-name()="t"]')|ForEach-Object{$_.InnerText});$shared+=($parts-join'')}}
  $reader=New-Object IO.StreamReader($sheet.Open());[xml]$sheetXml=$reader.ReadToEnd();$reader.Dispose();$rows=@()
  foreach($row in $sheetXml.SelectNodes('//*[local-name()="sheetData"]/*[local-name()="row"]')){$values=@{};foreach($cell in $row.SelectNodes('./*[local-name()="c"]')){$index=Get-ColumnNumber $cell.r;$type=[string]$cell.t;$value='';if($type-eq'inlineStr'){$value=(@($cell.SelectNodes('.//*[local-name()="t"]')|ForEach-Object{$_.InnerText})-join'')}else{$node=$cell.SelectSingleNode('./*[local-name()="v"]');if($node){$value=$node.InnerText;if($type-eq's' -and $value-ne''){$value=$shared[[int]$value]}}};$values[$index]=[string]$value};$rows+=,$values}
  if($rows.Count-lt2){throw 'Excel 沒有可讀取的商品資料。'};$header=$rows[0];$aliases=@{id=@('商品ID','商品 ID','商品編號');name=@('商品名稱','商品名');main=@('主商品圖片','商品主圖');image1=@('商品圖片1','商品圖片 1');image2=@('商品圖片2','商品圖片 2');image3=@('商品圖片3','商品圖片 3');image4=@('商品圖片4','商品圖片 4');image5=@('商品圖片5','商品圖片 5');image6=@('商品圖片6','商品圖片 6');image7=@('商品圖片7','商品圖片 7');image8=@('商品圖片8','商品圖片 8')};$columns=@{}
  foreach($key in $aliases.Keys){foreach($column in $header.Keys){if($aliases[$key]-contains([string]$header[$column]).Trim()){$columns[$key]=$column;break}}};if(-not$columns.ContainsKey('id')-or-not$columns.ContainsKey('name')-or-not$columns.ContainsKey('main')){throw '找不到必要欄位：商品ID、商品名稱、主商品圖片。請確認這是蝦皮媒體資訊 Excel。'}
  $products=@();for($rowIndex=1;$rowIndex-lt$rows.Count;$rowIndex++){$data=$rows[$rowIndex];$productId=if($data.ContainsKey($columns.id)){([string]$data[$columns.id]).Trim()}else{''};if(-not(Test-ProductId $productId)){continue};$urls=New-Object Collections.Generic.List[string];foreach($key in @('main','image1','image2','image3','image4','image5','image6','image7','image8')){if($columns.ContainsKey($key)-and$data.ContainsKey($columns[$key])){$url=([string]$data[$columns[$key]]).Trim();if($url-match'^https?://'){$urls.Add($url)}}};$name=if($data.ContainsKey($columns.name)){[string]$data[$columns.name]}else{''};$products+=,[pscustomobject]@{product_id=$productId;product_name=$name;image_urls=@($urls)}}
  if($products.Count-eq0){throw '沒有找到有效商品。商品ID必須是數字，圖片必須是 http/https 網址。'};return @($products)
 }catch{throw "讀取 Excel 失敗（原檔未被修改）：$($_.Exception.Message)"}finally{if($archive){$archive.Dispose()}}
}

function Save-ImportedCatalog([string]$ExcelPath){$products=Import-ShopeeExcel $ExcelPath;$workspace=Get-Workspace;$catalog=[ordered]@{source_excel=(Resolve-Path -LiteralPath $ExcelPath).Path;imported_at=(Get-Date).ToString('o');products=$products};$catalog|ConvertTo-Json -Depth 8|Set-Content (Join-Path $workspace 'catalog.json') -Encoding UTF8;return $products}
function Get-Catalog{$path=Join-Path (Get-Workspace) 'catalog.json';if(-not(Test-Path $path)){throw '尚未匯入蝦皮 Excel，請先選主選單 3。'};return (Get-Content $path -Raw -Encoding UTF8|ConvertFrom-Json)}
function Select-ShopeeProduct([string]$ProductId){Assert-ProductId $ProductId;$catalog=Get-Catalog;$matches=@($catalog.products|Where-Object product_id -eq $ProductId);if($matches.Count-ne1){throw '找不到該商品ID，或 Excel 中有重複商品ID。'};$selection=[ordered]@{product_id=$matches[0].product_id;product_name=$matches[0].product_name;image_urls=@($matches[0].image_urls);selected_at=(Get-Date).ToString('o')};$selection|ConvertTo-Json -Depth 5|Set-Content (Join-Path (Get-Workspace) 'selected_product.json') -Encoding UTF8;return[pscustomobject]$selection}
function Get-SelectedProduct{$path=Join-Path (Get-Workspace) 'selected_product.json';if(-not(Test-Path $path)){throw '尚未選擇商品，請先選主選單 4。'};$product=Get-Content $path -Raw -Encoding UTF8|ConvertFrom-Json;Assert-ProductId $product.product_id;return$product}

function Get-ImageInfo([string]$Path){Add-Type -AssemblyName System.Drawing;$stream=[IO.File]::OpenRead($Path);$image=$null;try{$image=[Drawing.Image]::FromStream($stream,$true,$true);return[pscustomobject]@{width=$image.Width;height=$image.Height;length=(Get-Item $Path).Length;hash=(Get-FileHash $Path -Algorithm SHA256).Hash}}finally{if($image){$image.Dispose()};$stream.Dispose()}}
function Download-ProductImages($Product){Assert-ProductId $Product.product_id;$rawDir=Join-Path (Get-Workspace) "raw_images\$($Product.product_id)";New-Item -ItemType Directory $rawDir -Force|Out-Null;$downloaded=New-Object Collections.Generic.List[string];$failures=New-Object Collections.Generic.List[string];$index=0
 foreach($url in @($Product.image_urls)){$name=if($index-eq0){'00_main_original.jpg'}else{'{0:D2}_detail_original.jpg'-f$index};$target=Join-Path $rawDir $name;if(Test-Path $target){try{Get-ImageInfo $target|Out-Null;$downloaded.Add($target);$index++;continue}catch{Remove-Item $target -Force}};$ok=$false;for($attempt=1;$attempt-le3;$attempt++){try{Invoke-WebRequest -Uri $url -OutFile "$target.part" -UseBasicParsing -TimeoutSec 60;Move-Item "$target.part" $target -Force;Get-ImageInfo $target|Out-Null;$downloaded.Add($target);$ok=$true;break}catch{Remove-Item "$target.part" -Force -ErrorAction SilentlyContinue;if($attempt-lt3){Start-Sleep -Seconds @(2,5)[$attempt-1]}}};if(-not$ok){$failures.Add($url);Write-TinySnowLog '原圖下載' $url "product_id=$($Product.product_id)" $false '下載3次仍失敗'};$index++}
 if($downloaded.Count-eq0){throw '所有原始圖片皆下載失敗，無法繼續。'};return[pscustomobject]@{paths=@($downloaded);failed_urls=@($failures);folder=$rawDir}}

function Analyze-ProductImages([string]$ProductId,[string[]]$Paths){Assert-ProductId $ProductId;$seen=New-Object Collections.Generic.HashSet[string];$items=New-Object Collections.Generic.List[object];$position=0
 foreach($imagePath in $Paths){$info=Get-ImageInfo $imagePath;$duplicate=-not$seen.Add($info.hash);$pixels=[long]$info.width*[long]$info.height;$squareScore=1-[Math]::Min(1,[Math]::Abs(($info.width/[double]$info.height)-1));$score=[Math]::Round(($pixels/1000000.0)+$squareScore,3);$items.Add([pscustomobject]@{path=$imagePath;file=(Split-Path $imagePath -Leaf);position=$position;width=$info.width;height=$info.height;bytes=$info.length;sha256=$info.hash;duplicate=$duplicate;technical_score=$score});$position++}
 $main=@($items|Where-Object position -eq0|Select-Object -First 1);$details=@($items|Where-Object{$_.position-ne0-and-not$_.duplicate}|Sort-Object technical_score -Descending);$ordered=New-Object Collections.Generic.List[string];if($main){$ordered.Add($main[0].path)};foreach($item in $details){$ordered.Add($item.path)};$analysis=[ordered]@{product_id=$ProductId;analyzed_at=(Get-Date).ToString('o');method='檢查可開啟性、尺寸、畫素、1:1接近度、SHA256重複；主圖優先，其餘不按原順序而依技術品質排序。語意真偽由保守提示詞交給圖像模型處理。';needs_manual_confirmation=$false;images=@($items);reference_order=@($ordered)};$analysis|ConvertTo-Json -Depth 8|Set-Content (Join-Path (Split-Path $Paths[0] -Parent) 'analysis.json') -Encoding UTF8;return[pscustomobject]$analysis}

function Get-CheckpointPath([string]$ProductId){Assert-ProductId $ProductId;$dir=Join-Path (Get-Workspace) "checkpoints\$ProductId";New-Item -ItemType Directory $dir -Force|Out-Null;return(Join-Path $dir 'checkpoint.json')}
function Get-Checkpoint([string]$ProductId){$path=Get-CheckpointPath $ProductId;if(Test-Path $path){return(Get-Content $path -Raw -Encoding UTF8|ConvertFrom-Json)};$states=[ordered]@{};foreach($slot in @('main','detail1','detail2','detail3','detail4')){$states[$slot]=[ordered]@{status='pending';retries=0;last_error=''}};$checkpoint=[ordered]@{product_id=$ProductId;states=$states;updated_at=(Get-Date).ToString('o')};$checkpoint|ConvertTo-Json -Depth 8|Set-Content $path -Encoding UTF8;return(Get-Content $path -Raw|ConvertFrom-Json)}
function Save-Checkpoint($Checkpoint){Assert-ProductId $Checkpoint.product_id;$Checkpoint.updated_at=(Get-Date).ToString('o');$Checkpoint|ConvertTo-Json -Depth 8|Set-Content (Get-CheckpointPath $Checkpoint.product_id) -Encoding UTF8}
function Test-Retryable([string]$Message){return $Message-match'429|HTTP 5\d\d|timed? out|逾時|network|連線|connection|temporar'}
function Convert-ToFinalJpeg([string]$Source,[string]$Target){$info=Get-ImageInfo $Source;if($info.width-lt100-or$info.height-lt100){throw '圖片尺寸異常（小於100像素）。'};$ratio=$info.width/[double]$info.height;if($ratio-lt.9-or$ratio-gt1.1){throw "圖片不是接近1:1（$($info.width)x$($info.height)）。"};Add-Type -AssemblyName System.Drawing;$image=[Drawing.Image]::FromFile($Source);try{$image.Save($Target,[Drawing.Imaging.ImageFormat]::Jpeg)}finally{$image.Dispose()};$result=Get-ImageInfo $Target;if($result.length-eq0){throw '輸出圖片為0KB。'};return$result}

function Get-Prompt([string]$Slot,[string]$Name){$templates=Get-Content (Join-Path (Get-Root) 'config\prompt_templates.json') -Raw -Encoding UTF8|ConvertFrom-Json;$key=switch($Slot){'main'{'main_image'}'detail1'{'detail_overview'}'detail2'{'detail_structure'}'detail3'{'detail_scene'}'detail4'{'detail_spec'}default{'detail_general'}};return "商品名稱僅供辨識：$Name。`n$($templates.$key)`n共同硬規則：$($templates.common_rules)"}
function Write-ProductReport($Product,$Checkpoint,[datetime]$Started,[string[]]$Errors){$dir=Join-Path (Get-Root) 'reports';New-Item -ItemType Directory $dir -Force|Out-Null;$done=@($Checkpoint.states.PSObject.Properties|Where-Object{$_.Value.status-eq'done'}).Count;$lines=@("商品ID：$($Product.product_id)","商品名稱：$($Product.product_name)","原圖數：$(@($Product.image_urls).Count)","生成成功數：$done");foreach($slot in @('main','detail1','detail2','detail3','detail4')){$lines+="$slot 狀態：$($Checkpoint.states.$slot.status)"};$lines+="總耗時：$([int]((Get-Date)-$Started).TotalSeconds) 秒";$lines+="錯誤：$($Errors-join'；')";$lines+="輸出資料夾：$(Join-Path (Get-Workspace) "final_images\$($Product.product_id)")";$lines|Set-Content (Join-Path $dir "$($Product.product_id)_report.txt") -Encoding UTF8}
function New-ProductZip([string]$ProductId){Assert-ProductId $ProductId;$folder=Join-Path (Get-Workspace) "final_images\$ProductId";$names=@("${ProductId}_main.jpg","${ProductId}_detail1.jpg","${ProductId}_detail2.jpg","${ProductId}_detail3.jpg","${ProductId}_detail4.jpg");foreach($name in $names){if(-not(Test-Path (Join-Path $folder $name))){throw "尚未完成5張圖片，缺少：$name"}};$zip=Join-Path (Get-Workspace) "${ProductId}_圖片優化完成.zip";if(Test-Path $zip){Remove-Item $zip -Force};Add-Type -AssemblyName System.IO.Compression.FileSystem;$temporary=Join-Path (Get-Workspace) "zip_$ProductId";Remove-Item $temporary -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory $temporary|Out-Null;foreach($name in $names){Copy-Item (Join-Path $folder $name) $temporary};[IO.Compression.ZipFile]::CreateFromDirectory($temporary,$zip);Remove-Item $temporary -Recurse -Force;return$zip}

function Start-SingleProductOptimization($Config){if(-not[bool]$Config.safe_test_mode){throw 'V2第二階段強制使用 SAFE_TEST_MODE，請保持開啟。'};$product=Get-SelectedProduct;Assert-ProductId $product.product_id;$started=Get-Date;$download=Download-ProductImages $product;$paths=@($download.paths);$analysis=Analyze-ProductImages $product.product_id $paths;if($analysis.needs_manual_confirmation){throw '原圖資訊可能互相衝突：需要人工確認。已停止生成。'};$maximum=[Math]::Min([Math]::Max(1,[int]$Config.max_reference_images),$paths.Count);$references=@($analysis.reference_order|Select-Object -First $maximum);$finalDir=Join-Path (Get-Workspace) "final_images\$($product.product_id)";New-Item -ItemType Directory $finalDir -Force|Out-Null;$checkpoint=Get-Checkpoint $product.product_id;$errors=New-Object Collections.Generic.List[string];$generated=0;$hashes=New-Object Collections.Generic.HashSet[string]
 foreach($slot in @('main','detail1','detail2','detail3','detail4')){$target=Join-Path $finalDir "$($product.product_id)_$slot.jpg";$state=$checkpoint.states.$slot;if($state.status-eq'done' -and(Test-Path $target)){try{$existing=Get-ImageInfo $target;$null=$hashes.Add($existing.hash);continue}catch{$state.status='pending'}};$state.status='generating';Save-Checkpoint $checkpoint;$prompt=Get-Prompt $slot $product.product_name;$success=$false
  for($attempt=1;$attempt-le3;$attempt++){try{$temporary=Invoke-ImageEditMulti $Config $references $prompt '1024x1024' 'medium';$info=Convert-ToFinalJpeg $temporary $target;Remove-Item $temporary -Force -ErrorAction SilentlyContinue;if($hashes.Contains($info.hash)){Remove-Item $target -Force;throw '生成圖片與本商品先前成品完全重複。'};$null=$hashes.Add($info.hash);$state.status='done';$state.last_error='';$generated++;$success=$true;Save-Checkpoint $checkpoint;break}catch{$state.retries=[int]$state.retries+1;$state.last_error=Protect-SecretText $_.Exception.Message ([string]$Config.api_key);Save-Checkpoint $checkpoint;if($attempt-lt3-and(Test-Retryable $state.last_error)){Start-Sleep -Seconds @(15,30)[$attempt-1]}else{break}}}
  if(-not$success){$state.status='failed';$errors.Add("$slot：$($state.last_error)");Save-Checkpoint $checkpoint;break}
 }
 Write-ProductReport $product $checkpoint $started @($errors);$allDone=@($checkpoint.states.PSObject.Properties|Where-Object{$_.Value.status-ne'done'}).Count-eq0;$zip='';if($allDone){$zip=New-ProductZip $product.product_id};return[pscustomobject]@{product_id=$product.product_id;generated_this_run=$generated;complete=$allDone;zip=$zip;failed_urls=@($download.failed_urls)}
}

Export-ModuleMember -Function Import-ShopeeExcel,Save-ImportedCatalog,Get-Catalog,Select-ShopeeProduct,Get-SelectedProduct,Download-ProductImages,Analyze-ProductImages,Get-Checkpoint,New-ProductZip,Start-SingleProductOptimization,Test-ProductId,Get-ImageInfo
