param(
  [Parameter(Mandatory=$true)][string]$OutDir,
  [Parameter(Mandatory=$true)][string]$ArtifactDir
)
$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[Text.Encoding]::UTF8
$MaxPaidRequests=20
$Locked=@('42833435408','52915734564','57565745174','58015741169')
$systemRoot=Split-Path $PSScriptRoot -Parent
. (Join-Path $systemRoot 'start\api_v2.ps1')
$key=[string]$env:TINYSNOW_API_KEY
if([string]::IsNullOrWhiteSpace($key)){throw 'BLOCK_MISSING_GENERATION_EXECUTOR: TINYSNOW_API_KEY repository secret is missing.'}
$config=[pscustomobject]@{api_key=$key;base_url='https://tinysnow.one/v1';model='gpt-image-2';quality='medium';size='1024x1024';safe_test_mode=$true;max_reference_images=2;transport_profile='r3_120s_safe'}
$OutDir=(Resolve-Path $OutDir).Path
New-Item -ItemType Directory -Path $ArtifactDir -Force|Out-Null
$sourceDir=Join-Path $ArtifactDir 'sources'; $outputDir=Join-Path $ArtifactDir 'outputs'; $reviewDir=Join-Path $ArtifactDir 'review'
foreach($d in @($sourceDir,$outputDir,$reviewDir)){New-Item -ItemType Directory -Path $d -Force|Out-Null}

function Read-Jsonl([string]$Path){
  $arr=@()
  if(Test-Path -LiteralPath $Path){foreach($line in Get-Content -LiteralPath $Path -Encoding UTF8){if(-not [string]::IsNullOrWhiteSpace($line)){$arr+=($line|ConvertFrom-Json)}}}
  return @($arr)
}
function Add-Jsonl([string]$Path,$Object){$line=$Object|ConvertTo-Json -Depth 40 -Compress;Add-Content -LiteralPath $Path -Value $line -Encoding UTF8}
function Get-FileSha([string]$Path){return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Detect-ImageExtension([string]$Path){
  $b=[IO.File]::ReadAllBytes($Path)
  if($b.Length-ge3 -and $b[0]-eq0xFF -and $b[1]-eq0xD8 -and $b[2]-eq0xFF){return '.jpg'}
  if($b.Length-ge8 -and $b[0]-eq0x89 -and $b[1]-eq0x50 -and $b[2]-eq0x4E -and $b[3]-eq0x47){return '.png'}
  if($b.Length-ge12 -and [Text.Encoding]::ASCII.GetString($b,0,4)-eq'RIFF' -and [Text.Encoding]::ASCII.GetString($b,8,4)-eq'WEBP'){return '.webp'}
  return $null
}
function Strip-FactPrefix([string]$Text){if($Text -match '^[^:]{1,40}:\s*(.+)$'){return [string]$Matches[1]};return $Text}
function Build-Prompt($slot,$reg){
  $lines=@();foreach($x in @($slot.display_text_allowlist)){$src=Strip-FactPrefix ([string]$x.source_text);$dst=Strip-FactPrefix ([string]$x.text);if(-not [string]::IsNullOrWhiteSpace($src) -and -not [string]::IsNullOrWhiteSpace($dst)){$lines+=('IF AND ONLY IF the exact source text is visibly present, replace "'+$src+'" with "'+$dst+'". Do not add it if absent.')}}
  $guardLines=@();foreach($g in @($reg.blocked_error_patterns)){if(-not[string]::IsNullOrWhiteSpace([string]$g)){$guardLines+=('Never repeat rejected pattern: '+[string]$g)}};foreach($g in @($reg.product_specific_guards)){if(-not[string]::IsNullOrWhiteSpace([string]$g)){$guardLines+=('Never perform rejected change: '+[string]$g)}}
  $base=@('Edit the exact provided source image only. The product identity is immutable.','Preserve the exact product body, shape, structure, colors, pattern, logo, brand, model, product quantity, and existing accessories.','Do not invent or add dimensions, material, functions, accessories, pockets, zippers, gifts, brands, certifications, performance claims, or unverified use scenes.','Do not borrow facts, visual details, or text from any other product.','Do not add any factual text except the explicit allowlist replacements below.','Preserve all existing English, model identifiers, SKU-like strings, and verified numeric tokens unless an exact allowlist replacement explicitly says otherwise.')
  if([string]$slot.action-eq'PROCESS_LOCALIZE'){$base+=@('This is source-preserving localization, not a product redraw. Allowed changes are Traditional Chinese localization, layout cleanup, whitespace improvement, slight repositioning, background cleanup, and product emphasis without changing the product.')}else{$base+=@('This is a SAFE_DERIVATIVE from the exact parent image. Only crop, reframe, safe zoom, reposition, background treatment, layout variation, and allowlisted text re-layout are allowed. Never redesign the product.')}
  if($lines.Count-eq0){$base+='No new product text is authorized. Keep existing factual text unchanged unless removal is necessary for layout safety.'}else{$base+='AUTHORIZED TEXT REPLACEMENTS:';$base+=$lines}
  if($guardLines.Count-gt0){$base+='REGRESSION GUARDS (prohibitions only; these are not product facts):';$base+=$guardLines}
  return ($base -join "`n")
}
function Test-OutputDecode([string]$Path){try{Add-Type -AssemblyName System.Drawing;$img=[System.Drawing.Image]::FromFile($Path);try{$ok=($img.Width-gt0 -and $img.Height-gt0);return [pscustomobject]@{ok=$ok;width=[int]$img.Width;height=[int]$img.Height;format=[string]$img.RawFormat.Guid}}finally{$img.Dispose()}}catch{return [pscustomobject]@{ok=$false;width=0;height=0;format='DECODE_FAIL'}}}

$selection=Get-Content -LiteralPath (Join-Path $OutDir 'canary_selection.json') -Raw -Encoding UTF8|ConvertFrom-Json
$slots=Read-Jsonl (Join-Path $OutDir 'canary_slot_manifest.jsonl')
if([int]$selection.selected_product_count-gt5 -or [int]$selection.selected_paid_slot_count-gt$MaxPaidRequests){throw 'Canary paid selection hard limit exceeded.'}
if(@($slots).Count-ne[int]$selection.selected_paid_slot_count){throw 'Canary slot manifest count mismatch.'}
foreach($s in $slots){if($Locked -contains [string]$s.product_id){throw ('Locked product selected: '+[string]$s.product_id)}}
$payloadRows=Read-Jsonl '_system/v4c/generation_payload/provider_neutral_payload.jsonl';$ctxRows=Read-Jsonl '_system/v4c/generation_payload/generation_context.jsonl';$readinessRows=Read-Jsonl '_system/v4c/generation_payload/product_execution_readiness.jsonl'
$payloadMap=@{};foreach($p in $payloadRows){$payloadMap[([string]$p.identity.product_id+':'+[string]$p.identity.slot)]=$p};$ctxMap=@{};foreach($c in $ctxRows){$ctxMap[([string]$c.identity.product_id+':'+[string]$c.identity.slot)]=$c};$readyMap=@{};foreach($r in $readinessRows){$readyMap[[string]$r.product_id]=$r}
$ledgerPath=Join-Path $OutDir 'paid_request_ledger.jsonl';$reqPath=Join-Path $OutDir 'provider_request_manifest.jsonl';$resultPath=Join-Path $OutDir 'generation_results.jsonl';$provPath=Join-Path $OutDir 'output_provenance.jsonl';$dqaPath=Join-Path $OutDir 'deterministic_qa.jsonl';$fqaPath=Join-Path $OutDir 'factual_regression_qa.jsonl';$humanPath=Join-Path $OutDir 'human_review_manifest.jsonl'
$existingLedger=Read-Jsonl $ledgerPath;$successfulIds=@{};foreach($l in $existingLedger){if([string]$l.status-eq'SUCCESS'){$successfulIds[[string]$l.generation_request_id]=$true}};$paidCount=@($existingLedger|Where-Object{$_.request_sent-eq$true}).Count;if($paidCount-gt$MaxPaidRequests){throw 'Existing persistent paid ledger already exceeds hard limit.'}

try{[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12}catch{}
$sourceMap=@{};$preflightFailures=@{}
foreach($s in $slots){$seq=[string]$s.source_sequence;if($sourceMap.ContainsKey($seq)){continue};$tmp=Join-Path $sourceDir ('seq_'+$seq+'.download');try{$wc=New-Object Net.WebClient;try{$wc.DownloadFile([string]$s.source_url,$tmp)}finally{$wc.Dispose()};$actual=Get-FileSha $tmp;if($actual-ne([string]$s.source_sha256).ToLowerInvariant()){$preflightFailures[$seq]='SOURCE_CHANGED_CANARY_HOLD';Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue;continue};$ext=Detect-ImageExtension $tmp;if($null-eq$ext){$preflightFailures[$seq]='CANARY_PRECHECK_HOLD';Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue;continue};$final=Join-Path $sourceDir ('seq_'+$seq+$ext);Move-Item -LiteralPath $tmp -Destination $final -Force;$sourceMap[$seq]=$final}catch{$preflightFailures[$seq]='CANARY_PRECHECK_HOLD';Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}}

$outputShaSeen=@{}
foreach($s in $slots){
  $pid=[string]$s.product_id;$slot=[string]$s.canonical_slot;$rid=[string]$s.generation_request_id;$k=$pid+':'+$slot;$seq=[string]$s.source_sequence
  if($successfulIds.ContainsKey($rid)){Add-Jsonl $resultPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status='IDEMPOTENT_EXISTING_SUCCESS_NO_RESEND';paid_api_called=$false;generated_at=(Get-Date).ToUniversalTime().ToString('o')});continue}
  $pre=@();if(-not$payloadMap.ContainsKey($k)){$pre+='PAYLOAD_MISSING'};if(-not$ctxMap.ContainsKey($k)){$pre+='CONTEXT_MISSING'};if(-not$readyMap.ContainsKey($pid) -or [string]$readyMap[$pid].status-ne'PRODUCT_READY_FOR_GENERATION'){$pre+='PRODUCT_NOT_READY'};if($Locked -contains $pid){$pre+='LOCKED_PRODUCT'}
  if(-not$sourceMap.ContainsKey($seq)){$reason=if($preflightFailures.ContainsKey($seq)){[string]$preflightFailures[$seq]}else{'CANARY_PRECHECK_HOLD'};Add-Jsonl $resultPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status=$reason;source_sequence=[int]$s.source_sequence;expected_source_sha256=[string]$s.source_sha256;request_sent=$false;paid_api_called=$false});continue}
  $sourcePath=[string]$sourceMap[$seq];$sourceSha=Get-FileSha $sourcePath;if($sourceSha-ne([string]$s.source_sha256).ToLowerInvariant()){$pre+='SOURCE_SHA_MISMATCH'}
  if([string]$s.action-eq'SAFE_DERIVATIVE'){if([string]::IsNullOrWhiteSpace([string]$s.parent_sha256) -or ([string]$s.parent_sha256).ToLowerInvariant()-ne$sourceSha){$pre+='PARENT_SHA_MISMATCH'}}
  if($payloadMap.ContainsKey($k)){$p=$payloadMap[$k];if([string]$p.identity.product_id-ne$pid){$pre+='PAYLOAD_PRODUCT_MISMATCH'};if([string]$p.identity.slot-ne$slot){$pre+='PAYLOAD_SLOT_MISMATCH'};if([int]$p.identity.source_sequence-ne[int]$s.source_sequence){$pre+='PAYLOAD_SEQUENCE_MISMATCH'};if(([string]$p.identity.source_sha256).ToLowerInvariant()-ne$sourceSha){$pre+='PAYLOAD_SHA_MISMATCH'};$pv=[string](ConvertTo-Json -InputObject @($p.identity.variant_scope) -Compress);$sv=[string](ConvertTo-Json -InputObject @($s.variant_scope) -Compress);if($pv-ne$sv){$pre+='PAYLOAD_VARIANT_MISMATCH'}}
  if($ctxMap.ContainsKey($k)){$c=$ctxMap[$k];if([string]$c.identity.product_id-ne$pid -or [string]$c.identity.slot-ne$slot){$pre+='CONTEXT_IDENTITY_MISMATCH'};if(([string]$c.identity.source_sha256).ToLowerInvariant()-ne$sourceSha){$pre+='CONTEXT_SHA_MISMATCH'};$safe=@([string[]]$c.safe_fact_ids);foreach($bad in @($c.excluded_unknown_ids)+@($c.excluded_conflict_ids)+@($c.excluded_forbidden_ids)){if($safe -contains [string]$bad){$pre+='CONTEXT_FACT_LEAK'}}}
  $prodMeta=@($selection.selected_products|Where-Object{[string]$_.product_id-eq$pid})[0];$variantJson=[string](ConvertTo-Json -InputObject @($s.variant_scope) -Compress);$regRaw=& python _system/memory/memory_runtime.py regression --memory _system/memory --product-id $pid --category ([string]$prodMeta.category) --subcategory ([string]$prodMeta.subcategory) --variant-scope-json $variantJson;if($LASTEXITCODE-ne0){$pre+='REGRESSION_CHECK_ERROR';$reg=$null}else{$reg=($regRaw -join "`n")|ConvertFrom-Json};if($null-ne$reg -and [bool]$reg.locked_product){$pre+='REGRESSION_LOCKED_PRODUCT'};if($paidCount-ge$MaxPaidRequests){$pre+='PAID_REQUEST_BUDGET_EXHAUSTED'}
  if($pre.Count-gt0){$status=if($pre -contains 'PARENT_SHA_MISMATCH'){'PARENT_SHA_MISMATCH_CANARY_HOLD'}else{'CANARY_PRECHECK_HOLD'};Add-Jsonl $resultPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status=$status;precheck_reasons=@($pre|Select-Object -Unique);request_sent=$false;paid_api_called=$false});continue}
  $prompt=Build-Prompt $s $reg;$shaAlg=New-Object Security.Cryptography.SHA256Managed;try{$promptSha=[BitConverter]::ToString($shaAlg.ComputeHash([Text.Encoding]::UTF8.GetBytes($prompt))).Replace('-','').ToLowerInvariant()}finally{$shaAlg.Dispose()}
  Add-Jsonl $reqPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;canonical_slot=$slot;source_sha256=$sourceSha;parent_sha256=$s.parent_sha256;variant_scope=@($s.variant_scope);action=$s.action;provider='TinySnow';endpoint='images/edits';model='gpt-image-2';quality='medium';size='1024x1024';provider_neutral_payload_sha256=$s.provider_neutral_payload_sha256;prompt_sha256=$promptSha;prompt=$prompt;safe_fact_ids=@($s.safe_fact_ids);display_text_ids=@($s.display_text_ids);regression_guards=$reg;adapter_does_not_infer_facts=$true})
  if($paidCount-ge$MaxPaidRequests){throw 'MAX_PAID_REQUESTS guard triggered immediately before provider submission.'};$paidCount++;$attempt=1;$ledgerBase=[ordered]@{generation_request_id=$rid;product_id=$pid;canonical_slot=$slot;source_sha256=$sourceSha;variant_scope=@($s.variant_scope);provider_neutral_payload_sha256=$s.provider_neutral_payload_sha256;provider='TinySnow';attempt_number=$attempt;request_sent=$true;paid_request_ordinal=$paidCount;submitted_at=(Get-Date).ToUniversalTime().ToString('o')}
  try{
    $generated=Invoke-ImageEditMultiV2 $config @($sourcePath) $prompt '1024x1024' 'medium';if(-not(Test-Path -LiteralPath $generated -PathType Leaf)){throw 'Provider returned no output file.'};$dest=Join-Path $outputDir ($pid+'_'+$slot+'_'+$rid+'.png');Copy-Item -LiteralPath $generated -Destination $dest -Force;$outSha=Get-FileSha $dest;$decode=Test-OutputDecode $dest;$dup=$outputShaSeen.ContainsKey($outSha);if(-not$dup){$outputShaSeen[$outSha]=$rid};$qaPass=([bool]$decode.ok -and (Get-Item -LiteralPath $dest).Length-gt0 -and -not$dup);$autoStatus=if($qaPass){'PASS'}else{'AUTO_QA_FAIL'}
    $ledger=[ordered]@{};foreach($name in $ledgerBase.Keys){$ledger[$name]=$ledgerBase[$name]};$ledger.status='SUCCESS';$ledger.output_sha256=$outSha;$ledger.provider_job_id=$null;$ledger.provider_job_id_status='NOT_EXPOSED_BY_EXISTING_SYNCHRONOUS_EXECUTOR';Add-Jsonl $ledgerPath ([pscustomobject]$ledger)
    Add-Jsonl $resultPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status='GENERATED_PENDING_QA';action=$s.action;output_sha256=$outSha;artifact_output=('outputs/'+(Split-Path $dest -Leaf));request_sent=$true;paid_api_called=$true;provider='TinySnow';attempt_number=$attempt})
    Add-Jsonl $provPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;source_sha256=$sourceSha;parent_sha256=$s.parent_sha256;output_sha256=$outSha;variant_scope=@($s.variant_scope);action=$s.action;safe_fact_ids=@($s.safe_fact_ids);display_text_ids=@($s.display_text_ids);regression_guards=$reg;provider='TinySnow';provider_request_job_id=$null;provider_request_job_id_status='NOT_EXPOSED_BY_EXISTING_SYNCHRONOUS_EXECUTOR';attempt_number=$attempt;generated_at=(Get-Date).ToUniversalTime().ToString('o');paid_request_count=$paidCount})
    Add-Jsonl $dqaPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status=$autoStatus;decode_pass=[bool]$decode.ok;width=$decode.width;height=$decode.height;non_empty=((Get-Item -LiteralPath $dest).Length-gt0);output_sha256=$outSha;provenance_complete=$true;mapping_correct=$true;request_id_unique=$true;duplicate_output=$dup;expected_format='PNG';provider_result_complete=$true;immutable_numeric_token_visual_audit='NOT_MACHINE_VERIFIABLE_REQUIRES_HUMAN'})
    Add-Jsonl $fqaPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;payload_regression_check='PASS';unknown_leak=0;conflict_leak=0;forbidden_leak=0;cross_product_leak=0;variant_leak=0;visual_status='NEEDS_HUMAN_VISUAL_QA';reason='No extra paid Vision/OCR inference authorized for generated visual inspection.'})
    Add-Jsonl $humanPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;action=$s.action;source_artifact=('sources/'+(Split-Path $sourcePath -Leaf));output_artifact=('outputs/'+(Split-Path $dest -Leaf));source_sha256=$sourceSha;output_sha256=$outSha;safe_fact_ids=@($s.safe_fact_ids);display_text_allowlist=@($s.display_text_allowlist);regression_guards=$reg;variant_scope=@($s.variant_scope);automatic_qa_result=$autoStatus;human_visual_status='PENDING_HUMAN_APPROVAL'})
  }catch{
    $msg=[string]$_.Exception.Message;$known=($msg -match 'HTTP\s+[45][0-9][0-9]');$status=if($known){'PROVIDER_FAILURE'}else{'PROVIDER_RESULT_AMBIGUOUS'};$ledger=[ordered]@{};foreach($name in $ledgerBase.Keys){$ledger[$name]=$ledgerBase[$name]};$ledger.status=$status;$ledger.output_sha256=$null;$ledger.provider_job_id=$null;$ledger.provider_job_id_status='NOT_EXPOSED_BY_EXISTING_SYNCHRONOUS_EXECUTOR';$ledger.error_type=$status;Add-Jsonl $ledgerPath ([pscustomobject]$ledger);Add-Jsonl $resultPath ([pscustomobject]@{generation_request_id=$rid;product_id=$pid;slot=$slot;status=$status;action=$s.action;request_sent=$true;paid_api_called=$true;provider='TinySnow';attempt_number=$attempt;retry_performed=$false;error_type=$status})
  }
}
$selRows=@($selection.selected_products);$html=@('<!doctype html><meta charset="utf-8"><title>TinySnow V4-C5.1 Canary Review</title><style>body{font-family:Arial,sans-serif;max-width:1400px;margin:auto;padding:20px}section{border-top:2px solid #222;margin-top:30px;padding-top:15px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:18px 0}.pair img{max-width:100%;max-height:520px;object-fit:contain;border:1px solid #bbb}.meta{white-space:pre-wrap;font-size:13px;background:#f6f6f6;padding:10px}</style><h1>TinySnow V4-C5.1 Canary Human Review</h1><p>GENERATION_SUCCESS != APPROVED. All outputs remain PENDING_HUMAN_APPROVAL.</p>');$humanRows=Read-Jsonl $humanPath
foreach($prod in $selRows){$pid=[string]$prod.product_id;$html+=('<section><h2>Product '+$pid+'</h2><p>Category: '+[string]$prod.category+' / '+[string]$prod.subcategory+'</p>');foreach($h in @($humanRows|Where-Object{[string]$_.product_id-eq$pid})){$src='../'+[string]$h.source_artifact;$dst='../'+[string]$h.output_artifact;$html+=('<h3>'+[string]$h.slot+' — '+[string]$h.action+'</h3><div class="pair"><div><b>Exact source</b><br><img src="'+$src+'"></div><div><b>Generated output</b><br><img src="'+$dst+'"></div></div>');$meta=[System.Net.WebUtility]::HtmlEncode(($h|ConvertTo-Json -Depth 12));$html+=('<div class="meta">'+$meta+'</div>')};$html+='</section>'}
$html+=@('<hr><h2>Human checklist</h2><ol><li>Same product identity</li><li>Structure unchanged</li><li>Colors/pattern unchanged</li><li>Logo/brand/model unchanged</li><li>Accessories/quantity unchanged</li><li>Traditional Chinese natural</li><li>No Simplified Chinese residue</li><li>Dimensions/numbers correct</li><li>No invented functions</li><li>Variant correct</li><li>Main image suitable for Taiwan e-commerce</li><li>Detail images sufficiently different but source-faithful</li></ol>');Set-Content -LiteralPath (Join-Path $reviewDir 'index.html') -Value ($html -join "`n") -Encoding UTF8;Copy-Item -LiteralPath (Join-Path $OutDir 'canary_selection.json') -Destination (Join-Path $reviewDir 'canary_selection.json') -Force;Copy-Item -LiteralPath $humanPath -Destination (Join-Path $reviewDir 'human_review_manifest.jsonl') -Force
Write-Host ('V4-C5.1 paid requests actually sent: '+$paidCount+' / '+$MaxPaidRequests)
