param(
 [ValidateSet('Smoke','Final')][string]$Phase='Smoke',[string]$ProgressPath,[string]$SummaryPath,
 [string]$QueuePath='_system/v4c/results/semantic_evidence_queue.jsonl',[string]$SmokeManifestPath='_system/v4c/semantic/smoke/semantic_smoke_manifest.jsonl',
 [string]$WorkerResumeSummaryPath='',[string]$OutputPath='artifacts/semantic-validation.json',
 [string]$ExpectedStableHead='5d49f061e140813b3d229520e9e530f86b27b640',[string]$V4C1BaselineHead='a7447b792e65780bc95aa248b9e3a2fd0466f142'
)
$ErrorActionPreference='Stop'
function Read-Jsonl([string]$Path){if(-not(Test-Path $Path)){throw "Missing JSONL: $Path"};$items=@();Get-Content $Path -Encoding UTF8|ForEach-Object{if(-not[string]::IsNullOrWhiteSpace($_)){$items+=($_|ConvertFrom-Json)}};return $items}
function Assert-GitInvariant{
 git merge-base --is-ancestor $V4C1BaselineHead HEAD; if($LASTEXITCODE-ne 0){throw "Current V4-C2 HEAD is not descended from V4-C1 baseline $V4C1BaselineHead"}
 $stableLine=(git ls-remote origin refs/heads/tinysnow-tool-only);if([string]::IsNullOrWhiteSpace($stableLine)){throw 'Unable to resolve stable branch HEAD'};$stableHead=($stableLine -split '\s+')[0];if($stableHead-ne$ExpectedStableHead){throw "Stable HEAD changed: $stableHead"}
 $protected=@('_system/v4c/inventory/source_inventory.jsonl','_system/v4c/progress/v4c_source_progress.jsonl','_system/v4c/results/source_evidence.jsonl','_system/v4c/results/duplicate_map.json','_system/v4c/results/failed_sources.json','_system/v4c/results/semantic_evidence_queue.jsonl','_system/v4c/results/aggregate_summary.json','_system/v4c/results/validation.json','_system/start/api_v2.ps1')
 git diff --quiet $V4C1BaselineHead -- $protected;if($LASTEXITCODE-ne 0){throw 'V4-C1 protected evidence or api_v2.ps1 changed after baseline'};return $stableHead
}
$stableHead=Assert-GitInvariant;$queue=@(Read-Jsonl $QueuePath);if($queue.Count-ne1544){throw "V4-C1 semantic queue changed: $($queue.Count)"};$queueSeq=@{};foreach($q in $queue){$queueSeq[[int]$q.sequence]=$true}
$records=@(Read-Jsonl $ProgressPath);$seen=@{};$local=@();$reuse=@();$pass=@();$hold=@();$block=@()
foreach($r in $records){$seq=[int]$r.sequence;if($seen.ContainsKey($seq)){throw "Duplicate semantic progress sequence: $seq"};$seen[$seq]=$true;if([string]$r.schema_version-ne'v4c2.semantic-evidence.1'){throw "Schema version mismatch at $seq"};if([string]$r.semantic_status-notin@('DONE','REUSED','BLOCKED')){throw "Non-terminal semantic status at $seq"};if([string]$r.gate.status-notin@('PASS','HOLD','BLOCK')){throw "Invalid gate at $seq"};if([bool]$r.flags.image_generation_called-or[bool]$r.flags.tiny_snow_api_called-or[bool]$r.flags.paid_api_called-or[bool]$r.flags.vision_api_called){throw "Forbidden API flag at semantic sequence $seq"};if(-not[bool]$r.flags.local_model_only){throw "Semantic record is not local-model-only: $seq"};if([bool]$r.provenance.source_pipeline_redownload){throw "V4-C1 source pipeline redownload flag is true at $seq"}
 if([string]$r.analysis_mode-eq'LOCAL_SEMANTIC'){if(-not$queueSeq.ContainsKey($seq)){throw "LOCAL_SEMANTIC sequence not from pending queue: $seq"};$local+=$r}elseif([string]$r.analysis_mode-eq'SHA_REUSE'){if([bool]$r.provenance.semantic_image_fetch){throw "SHA_REUSE fetched image bytes: $seq"};if(-not[bool]$r.reuse.model_inference_reused){throw "SHA_REUSE did not declare model reuse: $seq"};$reuse+=$r}else{throw "Invalid analysis_mode at $seq"};if([string]$r.gate.status-eq'PASS'){$pass+=$r}elseif([string]$r.gate.status-eq'HOLD'){$hold+=$r}else{$block+=$r}}
$summary=Get-Content $SummaryPath -Raw -Encoding UTF8|ConvertFrom-Json;if([bool]$summary.image_generation_called-or[bool]$summary.tiny_snow_api_called-or[bool]$summary.paid_api_called-or[bool]$summary.vision_api_called){throw 'Summary contains forbidden API flag'};if([bool]$summary.source_pipeline_redownload){throw 'Summary says V4-C1 source pipeline was redownloaded'}
$checkpointResumeObserved=$false;$familyCount=$null;$subcategoryCount=$null;$uniqueProducts=$null
if($Phase-eq'Smoke'){
 $smoke=@(Read-Jsonl $SmokeManifestPath);if($smoke.Count-ne160){throw 'Smoke manifest count must be 160'};if($local.Count-ne160){throw "Smoke local semantic count must be 160; got $($local.Count)"};if($reuse.Count-ne1){throw "Smoke SHA reuse count must be exactly 1; got $($reuse.Count)"};$probe=@($reuse|Where-Object{[int]$_.sequence-eq13-and[int]$_.canonical_sequence-eq7});if($probe.Count-ne1){throw 'Smoke did not prove SHA reuse 13 -> 7'}
 $families=@{};$subcats=@{};$products=@{};foreach($s in $smoke){$families[[string]$s.family]=$true;$subcats[([string]$s.family+'/'+[string]$s.subcategory)]=$true;$products[[string]$s.product_id]=$true};$familyCount=$families.Count;$subcategoryCount=$subcats.Count;$uniqueProducts=$products.Count;if($familyCount-lt4-or$subcategoryCount-lt13-or$uniqueProducts-lt100){throw 'Smoke cross-category coverage invariant failed'}
 if([string]::IsNullOrWhiteSpace($WorkerResumeSummaryPath)-or-not(Test-Path $WorkerResumeSummaryPath)){throw 'Missing smoke checkpoint resume summary'};$resume=Get-Content $WorkerResumeSummaryPath -Raw -Encoding UTF8|ConvertFrom-Json;if([int]$resume.checkpoint_skipped_this_run-lt20){throw 'Checkpoint resume did not skip first 20 records'};if([int]$resume.covered_after_run-ne160){throw 'Checkpoint resume did not reconcile all 160 smoke records'};$checkpointResumeObserved=$true
 $technicalBlocks=@($block|Where-Object{$reasons=@($_.gate.reasons);($reasons-contains'FETCH_FAILED')-or($reasons-contains'SOURCE_SHA_MISMATCH')-or($reasons-contains'LOCAL_MODEL_UNAVAILABLE')-or($reasons-contains'LOCAL_MODEL_OR_DECODE_FAILURE')});if($technicalBlocks.Count-gt0){throw "Smoke has technical BLOCK records: $($technicalBlocks.Count)"};if([int]$summary.remaining_semantic-ne1384){throw "Smoke remaining should be 1384; got $($summary.remaining_semantic)"}
}else{
 if($local.Count-ne1544){throw "Final local semantic coverage must be 1544; got $($local.Count)"};if($reuse.Count-ne4){throw "Final SHA reuse coverage must be 4; got $($reuse.Count)"};foreach($pair in @(@(13,7),@(1469,1468),@(1533,1532),@(2307,2304))){$ok=@($reuse|Where-Object{[int]$_.sequence-eq[int]$pair[0]-and[int]$_.canonical_sequence-eq[int]$pair[1]});if($ok.Count-ne1){throw "Missing final SHA reuse $($pair[0]) -> $($pair[1])"}};if([int]$summary.remaining_semantic-ne0){throw "Final semantic remaining must be zero; got $($summary.remaining_semantic)"};$missing=@();foreach($q in $queue){if(-not$seen.ContainsKey([int]$q.sequence)){$missing+=[int]$q.sequence}};if($missing.Count-gt0){throw "Final missing V4-C1 pending semantic sequences: $($missing -join ',')"}
}
$result=[ordered]@{phase=$Phase;passed=$true;v4c1_baseline_head=$V4C1BaselineHead;stable_head=$stableHead;stable_head_unchanged=$true;v4c1_protected_files_unchanged=$true;api_v2_unchanged=$true;pending_queue_count=$queue.Count;local_semantic_count=$local.Count;sha_reuse_count=$reuse.Count;gate_pass=$pass.Count;gate_hold=$hold.Count;gate_block=$block.Count;checkpoint_resume_observed=$checkpointResumeObserved;smoke_family_count=$familyCount;smoke_subcategory_count=$subcategoryCount;smoke_unique_products=$uniqueProducts;image_generation_called=$false;tiny_snow_api_called=$false;paid_api_called=$false;vision_api_called=$false;local_model_only=$true;source_pipeline_redownload=$false};$dir=Split-Path -Parent $OutputPath;if($dir){New-Item -ItemType Directory -Force $dir|Out-Null};$result|ConvertTo-Json -Depth 20|Set-Content $OutputPath -Encoding UTF8
Write-Host "SEMANTIC_VALIDATION_PHASE=$Phase";Write-Host 'SEMANTIC_VALIDATION_PASSED=true';Write-Host "SEMANTIC_LOCAL_COUNT=$($local.Count)";Write-Host "SEMANTIC_SHA_REUSE=$($reuse.Count)";Write-Host "SEMANTIC_HOLD=$($hold.Count)";Write-Host "SEMANTIC_BLOCK=$($block.Count)";Write-Host 'IMAGE_GENERATION_CALLED=false';Write-Host 'TINY_SNOW_API_CALLED=false';Write-Host 'PAID_API_CALLED=false';Write-Host 'VISION_API_CALLED=false';Write-Host 'SOURCE_PIPELINE_REDOWNLOAD=false'
